In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.9855e-24,  4.5622e-41, -1.9855e-24],
        [ 4.5622e-41,  7.5244e+28,  6.7131e+22],
        [ 6.9771e+22,  7.5551e+31,  1.4353e-19],
        [ 1.2711e+31,  7.7447e+31,  8.3030e-33],
        [ 1.3563e-19,  1.8037e+28,  7.1833e+22]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1811, 0.8391, 0.5479],
        [0.7999, 0.7989, 0.8407],
        [0.9594, 0.5640, 0.0431],
        [0.8915, 0.6608, 0.3882],
        [0.3313, 0.1034, 0.5833]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.4642,  0.6699, -1.8378],
        [ 0.7664, -0.0380,  0.7646],
        [-0.4382,  0.0962,  1.3061],
        [ 0.7058, -0.3213,  0.4475],
        [-1.0241,  1.3764, -0.2444]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5,3)

In [10]:
print(x+y)

tensor([[ 0.5032,  1.5571, -1.6558],
        [ 1.6152,  0.3521,  1.4416],
        [-0.3174,  0.9012,  2.2526],
        [ 0.8623,  0.6111,  0.9460],
        [-0.3563,  1.9484,  0.4080]])


In [11]:
print(torch.add(x, y))

tensor([[ 0.5032,  1.5571, -1.6558],
        [ 1.6152,  0.3521,  1.4416],
        [-0.3174,  0.9012,  2.2526],
        [ 0.8623,  0.6111,  0.9460],
        [-0.3563,  1.9484,  0.4080]])


In [12]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5032,  1.5571, -1.6558],
        [ 1.6152,  0.3521,  1.4416],
        [-0.3174,  0.9012,  2.2526],
        [ 0.8623,  0.6111,  0.9460],
        [-0.3563,  1.9484,  0.4080]])


In [13]:
y

tensor([[0.0390, 0.8872, 0.1820],
        [0.8488, 0.3900, 0.6771],
        [0.1207, 0.8049, 0.9465],
        [0.1565, 0.9323, 0.4985],
        [0.6678, 0.5720, 0.6524]])

In [14]:
y.add_(x)
print(y)

tensor([[ 0.5032,  1.5571, -1.6558],
        [ 1.6152,  0.3521,  1.4416],
        [-0.3174,  0.9012,  2.2526],
        [ 0.8623,  0.6111,  0.9460],
        [-0.3563,  1.9484,  0.4080]])


In [15]:
print(x[:, 1])

tensor([ 0.6699, -0.0380,  0.0962, -0.3213,  1.3764])


In [16]:
x

tensor([[ 0.4642,  0.6699, -1.8378],
        [ 0.7664, -0.0380,  0.7646],
        [-0.4382,  0.0962,  1.3061],
        [ 0.7058, -0.3213,  0.4475],
        [-1.0241,  1.3764, -0.2444]])

In [17]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [21]:
x, y, z

(tensor([[ 1.2542, -0.0034, -0.9377, -0.1956],
         [-2.1779, -0.6938, -0.1716, -1.3227],
         [ 0.4809,  1.1910, -0.5094,  0.3726],
         [ 1.2499, -1.7157,  0.1365,  2.4475]]),
 tensor([ 1.2542, -0.0034, -0.9377, -0.1956, -2.1779, -0.6938, -0.1716, -1.3227,
          0.4809,  1.1910, -0.5094,  0.3726,  1.2499, -1.7157,  0.1365,  2.4475]),
 tensor([[ 1.2542, -0.0034, -0.9377, -0.1956, -2.1779, -0.6938, -0.1716, -1.3227],
         [ 0.4809,  1.1910, -0.5094,  0.3726,  1.2499, -1.7157,  0.1365,  2.4475]]))

In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0803])
-1.0802923440933228


In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [25]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [26]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [27]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([-0.0803], device='cuda:0')
tensor([-0.0803], dtype=torch.float64)
